# Generated by Django 3.2.6 on 2021-09-02 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_info', models.CharField(db_index=True, max_length=1000, verbose_name='Инфа о заказе')),
            ],
        ),
    ]
