# Generated by Django 3.2.6 on 2021-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210902_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_uuid',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='CDEK UUID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_info',
            field=models.CharField(db_index=True, max_length=10000, verbose_name='Инфа о заказе'),
        ),
    ]
