# Generated by Django 3.2.6 on 2021-09-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210903_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'We got your order!'), (2, 'Order is sent to carrier'), (3, 'Order is sent back to shop'), (4, 'Delivered')], default=1, verbose_name='Статус'),
        ),
    ]
